---
title: "Start of this blog"
author: sebastianschuster
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is the first sentence of my personal blog. 

You might wonder, why I decided to use English on my whole website and rejected to build it multi-lingual even though German is my mother tongue. The reason is two folded. First, I guess it would by inappropriately time consuming to build a multi-lingual website even if there are good translation tools around these days that would save me a lot of time. Second, I believe that writing this blog in English will make me spend more time thinking about the way I communicate my content. 

My intention is to use this blog as a tool of communication and documentation of my way to become a better R user. Therefore I will write about common problems I'm facing during my everyday work as a scientist working on real-world empirical data. Working as a research assistant apart of my studies helped me a lot to dig deeper into R, although it was a pain for more than one time, because I was used to work with example data sets instead of messy ones. To give you an idea of how I approach new data sets, I want to participate in the weekly [tidy tuesday](https://github.com/rfordatascience/tidytuesday) data project, every now and then. 



<!-- 
Notes:
- What I want to blog about

-->





